import { defineSidebar } from './types'

export const duckAuthSidebar = defineSidebar([
  {
    title: '',
    items: [
      { title: 'Introduction', href: '/duck-auth/introduction' },
      { title: 'Installation', href: '/duck-auth/installation' },
      { title: 'Concepts & glossary', href: '/duck-auth/concepts' },
      { title: 'How it compares', href: '/duck-auth/comparison' },
      { title: 'FAQ', href: '/duck-auth/faq' },
    ],
  },
  {
    title: 'Core',
    href: '/duck-auth/core',
    items: [
      { title: 'Overview', href: '/duck-auth/core' },
      { title: 'Sessions', href: '/duck-auth/core/sessions' },
      { title: 'Identities', href: '/duck-auth/core/identities' },
      { title: 'Flows', href: '/duck-auth/core/flows' },
      { title: 'Organizations', href: '/duck-auth/core/orgs' },
      { title: 'Delivery', href: '/duck-auth/core/delivery' },
      { title: 'Errors', href: '/duck-auth/core/errors' },
      { title: 'Events', href: '/duck-auth/core/events' },
      { title: 'Anomaly detection', href: '/duck-auth/core/anomaly' },
      { title: 'Compliance presets', href: '/duck-auth/core/compliance' },
      { title: 'Data at rest', href: '/duck-auth/core/data-at-rest' },
      { title: 'Captcha', href: '/duck-auth/core/captcha' },
      {
        title: 'Transports',
        href: '/duck-auth/core/transports',
        collapsible: true,
        defaultOpen: false,
        items: [
          { title: 'Overview', href: '/duck-auth/core/transports' },
          { title: 'CookieTransport', href: '/duck-auth/core/transports/cookie' },
          { title: 'BearerTransport', href: '/duck-auth/core/transports/bearer' },
          { title: 'JwtTransport', href: '/duck-auth/core/transports/jwt' },
          { title: 'CompositeTransport', href: '/duck-auth/core/transports/composite' },
          { title: 'DPoP', href: '/duck-auth/core/transports/dpop' },
        ],
      },
    ],
  },
  {
    title: 'Providers',
    href: '/duck-auth/providers',
    items: [
      { title: 'Overview', href: '/duck-auth/providers' },
      { title: 'Password', href: '/duck-auth/providers/password' },
      { title: 'Magic link', href: '/duck-auth/providers/magic-link' },
      {
        title: 'OAuth',
        href: '/duck-auth/providers/oauth',
        collapsible: true,
        defaultOpen: false,
        items: [
          { title: 'Overview', href: '/duck-auth/providers/oauth' },
          { title: 'Google', href: '/duck-auth/providers/oauth/google' },
          { title: 'GitHub', href: '/duck-auth/providers/oauth/github' },
          { title: 'Microsoft', href: '/duck-auth/providers/oauth/microsoft' },
          { title: 'Apple', href: '/duck-auth/providers/oauth/apple' },
          { title: 'LinkedIn', href: '/duck-auth/providers/oauth/linkedin' },
          { title: 'Discord', href: '/duck-auth/providers/oauth/discord' },
        ],
      },
      { title: 'Passkey', href: '/duck-auth/providers/passkey' },
      { title: 'API key', href: '/duck-auth/providers/api-key' },
      { title: 'SAML', href: '/duck-auth/providers/saml' },
    ],
  },
  {
    title: 'Adapters',
    href: '/duck-auth/adapters',
    items: [
      { title: 'Overview', href: '/duck-auth/adapters' },
      { title: 'Memory', href: '/duck-auth/adapters/memory' },
      { title: 'Drizzle', href: '/duck-auth/adapters/drizzle' },
      { title: 'Redis and Valkey', href: '/duck-auth/adapters/redis' },
    ],
  },
  {
    title: 'Server adapters',
    href: '/duck-auth/server',
    items: [
      { title: 'Overview', href: '/duck-auth/server' },
      { title: 'Express', href: '/duck-auth/server/express' },
      { title: 'Hono', href: '/duck-auth/server/hono' },
      { title: 'Next.js', href: '/duck-auth/server/next' },
      { title: 'Fastify', href: '/duck-auth/server/fastify' },
      { title: 'Koa', href: '/duck-auth/server/koa' },
      { title: 'Elysia', href: '/duck-auth/server/elysia' },
      { title: 'NestJS', href: '/duck-auth/server/nestjs' },
      { title: 'gRPC', href: '/duck-auth/server/grpc' },
      { title: 'Fetch runtimes', href: '/duck-auth/server/generic' },
    ],
  },
  {
    title: 'Client libraries',
    href: '/duck-auth/client',
    items: [
      { title: 'Overview', href: '/duck-auth/client' },
      { title: 'Vanilla', href: '/duck-auth/client/vanilla' },
      { title: 'React', href: '/duck-auth/client/react' },
      { title: 'Vue', href: '/duck-auth/client/vue' },
      { title: 'Svelte', href: '/duck-auth/client/svelte' },
      { title: 'Solid', href: '/duck-auth/client/solid' },
    ],
  },
  {
    title: 'Guides',
    items: [
      { title: 'Quick start', href: '/duck-auth/guides' },
      { title: 'Adding MFA', href: '/duck-auth/guides/mfa' },
      { title: 'Bridging to duck-iam', href: '/duck-auth/guides/iam-bridge' },
    ],
  },
  {
    title: 'Course',
    href: '/duck-auth/course',
    items: [
      { title: 'Chapter 1: your first sign-in', href: '/duck-auth/course/chapter-1' },
      { title: 'Chapter 2: accounts', href: '/duck-auth/course/chapter-2' },
      { title: 'Chapter 3: sessions', href: '/duck-auth/course/chapter-3' },
      { title: 'Chapter 4: behind HTTP', href: '/duck-auth/course/chapter-4' },
      { title: 'Chapter 5: in the browser', href: '/duck-auth/course/chapter-5' },
      { title: 'Chapter 6: more ways in', href: '/duck-auth/course/chapter-6' },
      { title: 'Chapter 7: a second factor', href: '/duck-auth/course/chapter-7' },
      { title: 'Chapter 8: production', href: '/duck-auth/course/chapter-8' },
    ],
  },
  {
    title: 'Advanced',
    items: [
      { title: 'Production hardening', href: '/duck-auth/advanced/security' },
      { title: 'Multi-tenancy', href: '/duck-auth/advanced/multi-tenancy' },
      { title: 'Webhooks', href: '/duck-auth/advanced/webhooks' },
      { title: 'OIDC discovery', href: '/duck-auth/advanced/oidc' },
      { title: 'OIDC provider', href: '/duck-auth/advanced/oidc-op' },
      { title: 'Testing', href: '/duck-auth/advanced/testing' },
    ],
  },
  {
    title: 'Changelog',
    items: [{ title: 'Changelog', href: '/duck-auth/changelog' }],
  },
])
